version: "3.9"

services:
  dinsights:
    build: .
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - DEVMODE=true
      - TALK_CHANNEL=bot_dev
    secrets:
      - token

secrets:
  token:
    file: ./token.txt
